name: run-release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Batch changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: batch auto

      - name: Merge changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: merge

      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: latest

      - name: Create tag
        run: |
          git tag "${{ steps.latest.outputs.output }}"
          git push origin "${{ steps.latest.outputs.output }}"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean --release-notes="changes/${{ steps.latest.outputs.output }}" --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GORELEASER_CURRENT_TAG: "${{ steps.latest.outputs.output }}"

      # Commit and push the updated CHANGELOG.md
      - name: Commit CHANGELOG
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git add .changes/
          git commit -m "Update CHANGELOG.md for ${{ steps.latest.outputs.output }} [skip ci]" || echo "No changes to commit"
          git push origin main